# If true, each camera's video directory contains only the video files. If false, each camera's video directory contains an additional subdirectory, which then contains the video files
vid_dir_flag: True

# Video file extension
extension: '.mp4'

# The number of frames in each video file. If only a single video file exists for each camera, set this to 1e10
chunks: 3000

io_config: io.yaml

# Number of channels for each input image (e.g. RGB == 3)
N_CHANNELS_IN: 3

# Number of network output channels.
N_CHANNELS_OUT: 1

# BATCH_SIZE*len(CAMNAMES) should be <= 6 for most COM training applications
BATCH_SIZE: 2

# COM training option. Sets the size of the 3D Guassians (in pixels) used as labels for the MAX models
SIGMA: 30

# COM training option. Sets the number of epochs during training
EPOCHS: 3

# DANNCE training option. Sets the verbosity of training output
VERBOSE: 1

# Degree of downsampling applied to image input. Default 1, other values untested.
DOWNFAC: 2

# DANNCE training option. Loss function to be used. Default MSE.
loss: mask_nan_keep_loss

# DANNCE training option. Learning rate for the Adam optimizer. Default 1e-3.
lr: 5e-5

# name of the network architecture (see nets.py)
net: unet2d_fullbn

# If true, each camera's video directory contains only the video files. If false, each camera's video directory contains an additional subdirectory, which then contains the video files
vid_dir_flag: True

# DANNCE training. Metric to be monitored in addition to loss
metric: mse

# Set the video extension
extension: .mp4

# How many samples from each animal do you want to (randomly) set aside for a validation metric?
num_validation_per_exp: 2

# If true, saves plots of the training labels overlaid on images
debug: False

# When using a system with multiple GPUs, we should just target one of them
gpuID: "0"

# Number of frames in each video file
chunks: 3000

# If present, write the confidence map output and image/COM overlays to disk during prediction
#COMdebug: Camera5

# How many frames to you want to predict over? Set to 'max' for all video frames.
max_num_samples: 1000

# Downsampling mode, 'dsm' is downsample local mean. 'nn' is nearest neighbor and potentially faster
dsmode: nn

com_finetune_weights: ./COM/weights/