RESULTSDIR: ./ 
datadir: ./data/ # path to folder containing formatted data files 

# path to folder contraining video sub directories
viddir: ./videos/

# names of data files. must match the order of CAMNAMES below
datafile: ['demo_indices', 'demo_indices', 'demo_indices', 'demo_indices, 'demo_indices', 'demo_indices']

# How to crop the input images. The U-Net expects each dimension size to be a multiple of 32.
CROP_HEIGHT: [0, 1024]

CROP_WIDTH: [20, 1300]
# Number of channels for each input image (e.g. RGB == 3)
N_CHANNELS_IN: 3

# Names for each of the camera subdirectories in the video folder. Order should match the datafiles above.
CAMNAMES: ['CameraR', 'CameraL', 'CameraU', 'CameraE', 'CameraS', 'CameraU2']

# path to folder with DANNCE formated camera calibration parameters
CALIBDIR: ./calibration/

# names of each camera calibration file. Order should match CAMNAMES and datafiles above
calib_file: ['hires_cam1_params.mat', 'hires_cam2_params.mat', 'hires_cam4_params.mat','hires_cam3_params.mat','hires_cam5_params.mat','hires_cam6_params.mat']

# If true, each camera's video directory contains only the video files. If false, each camera's video directory contains an additional subdirectory, which then contains the video files
vid_dir_flag: False

# Set GPU ID. If None, does not select a GPU
gpuID: "1"

# The number of frames in each video file
chunks: 3500

# Video file extension
extension: .mp4

# Path to the COMfinder CONFIG file
COM_CONFIG: ./COM/config.yaml
DANNCE_CONFIG: ./DANNCE/config.yaml

lbl_template: /home/twd/Dropbox/mocapdata_for_tim/CameraCalib_rd4/Recording_calibrated_hires/rat.template